### ISSUE TITLE
Feature Request: Turn lights on at device startup

### ISSUE THREAD

**Issue by jayden-hunter** [vchlum/nano-lights#5]
It would be awesome if the lights could be turned on after computer start-up has finished. (With a setting to turn this on/off)
If needed/desired, I would be happy to try implement this feature, with permission from you :)
Thanks!

**Comment by vchlum** [comment]
Hi @jayden-hunter ! Thank you for your offer. Currently, it would be better to postpone the implementation of the suggested feature. 

I have started working on a new plugin-based Gnome extension that will control multiple smart home devices such as Nanoleaf, Philips Hue, Ikea Dirigera, and possibly others... It will include features from nano-light (this extension), hue-lights (https://github.com/vchlum/hue-lights) and hopefully more. My idea is to deprecate the original extensions (nano-lights, hue-lights) in the future and support only the new extension. In the new extension, it should be easy to implement and add support for a new device brand.

The work is in the early stages. No promises right now... I can roughly say, I target Q1 2025 with its first release. Depends on my occupation. Once the new extension is published on GitHub, I would appreciate any help. Including the feature you mentioned.  :-)

**Comment by jayden-hunter** [comment]
Thanks for getting back to me so soon! In that case Ill wait patiently for your new extension. Thanks for your work on this app 😊
